targetUrl: "http://localhost"
targetPort: "9000"

blockedHeaders:
  - "X-Custom-Key"
  - "Accesstoken"

blockedQueryParams:
  - "filter"
  - "category"

maskedNeededKeys:
  - "address"
  - "authproviderid"
  - "bankaccount"
  - "birthdate"
  - "birthday"
  - "checkingaccount"
  - "cookie"
  - "credit"
  - "creditcard"
  - "dateofbirth"
  - "debit"
  - "debitcard"
  - "driverslicense"
  - "driverslicensenumber"
  - "ein"
  - "email"
  - "emailaddress"
  - "firstname"
  - "gender"
  - "ip"
  - "ipaddress"
  - "lastname"
  - "license"
  - "licensenumber"
  - "mac"
  - "macaddress"
  - "married"
  - "mobile"
  - "mobilenumber"
  - "name"
  - "pass"
  - "passport"
  - "passportnumber"
  - "password"
  - "phone"
  - "phonenumber"
  - "race"
  - "religion"
  - "routingnumber"
  - "savingsaccount"
  - "secret"
  - "socialsecurity"
  - "socialsecuritynumber"
  - "ssn"
  - "stateid"
  - "stateidnumber"
  - "street"
  - "streetaddress"
  - "taxidnumber"
  - "telephone"
  - "telephonenumber"
